### ISSUE TITLE
(node:9224) UnhandledPromiseRejectionWarning: Error: Node is either not visible or not an HTMLElement

### ISSUE THREAD

**Issue by Kyielas** [sell/discord-autotyper#1]
when i type node . it opens up the discord page and nothing happens, dosn't goto login and stuff.
already tried full screen and unfullscreen too

**Comment by Kyielas** [comment]
[https://www.imageupload.net/image/Xl2zS](url)

**Comment by Steby5** [comment]
> 
> 
> when i type node . it opens up the discord page and nothing happens, dosn't goto login and stuff.
> already tried full screen and unfullscreen too
same here

**Comment by sell** [comment]
should be fixed @Steby5 and @Kyielas

**Comment by sell** [comment]
closing, lmk if anything else occurs.
